### ISSUE TITLE
Node 0.11 build failure

### ISSUE THREAD

**Issue by postcasio** [mscdex/cap#17]
Build fails targeting node 0.11.13:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.13.1
gyp info using node@0.10.31 | darwin | x64
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dominic/test/cap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/dominic/.node-gyp/0.11.13/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/dominic/.node-gyp/0.11.13',
gyp info spawn args   '-Dmodule_root_dir=/Users/dominic/test/cap',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/cap/src/binding.o
../src/binding.cc:65:28: error: no member named 'New' in 'v8::String'
      Address->Set(String::New(key), Undefined());
                   ~~~~~~~~^
../src/binding.cc:67:28: error: no member named 'New' in 'v8::String'
      Address->Set(String::New(key), String::New(address));
                   ~~~~~~~~^
../src/binding.cc:71:21: error: expected class name
class Pcap : public ObjectWrap {
                    ^
../src/binding.cc:80:5: error: unknown type name 'uv_poll_t'
    uv_poll_t poll_handle;
    ^
../src/binding.cc:180:28: error: unknown type name 'uv_poll_t'
    static void cb_packets(uv_poll_t* handle, int status, int events) {
                           ^
../src/binding.cc:194:36: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> New(const Arguments& args) {
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/dominic/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:213:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Send(const Arguments& args) {
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/dominic/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:271:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Open(const Arguments& args) {
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/dominic/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:508:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
    static Handle<Value> Close(const Arguments& args) {
                                     ^~~~~~~~~
                                     v8::internal::Arguments
/Users/dominic/.node-gyp/0.11.13/deps/v8/include/v8.h:149:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/binding.cc:99:12: error: no member named 'Dispose' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
      Emit.Dispose();
      ~~~~ ^
../src/binding.cc:100:12: error: no member named 'Clear' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
      Emit.Clear();
      ~~~~ ^
../src/binding.cc:119:9: error: use of undeclared identifier 'Unref'
        Unref();
        ^
../src/binding.cc:128:19: error: calling a protected constructor of class 'v8::HandleScope'
      HandleScope scope;
                  ^
/Users/dominic/.node-gyp/0.11.13/deps/v8/include/v8.h:845:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/binding.cc:142:9: error: too few arguments to function call, expected 2, have 1; did you mean '::Pcap::New'?
        Number::New(copy_len),
        ^~~~~~~~~~~
        ::Pcap::New
../src/binding.cc:194:26: note: '::Pcap::New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/binding.cc:143:9: error: too few arguments to function call, expected 2, have 1; did you mean '::Pcap::New'?
        Boolean::New(truncated)
        ^~~~~~~~~~~~
        ::Pcap::New
../src/binding.cc:194:26: note: '::Pcap::New' declared here
    static Handle<Value> New(const Arguments& args) {
                         ^
../src/binding.cc:145:16: error: member reference type 'Persistent<v8::Function>' is not a pointer; maybe you meant to use '.'?
      obj->Emit->Call(obj->handle_, 3, emit_argv);
      ~~~~~~~~~^~
               .
../src/binding.cc:145:18: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
      obj->Emit->Call(obj->handle_, 3, emit_argv);
      ~~~~~~~~~  ^
../src/binding.cc:145:28: error: no member named 'handle_' in 'Pcap'
      obj->Emit->Call(obj->handle_, 3, emit_argv);
                      ~~~  ^
../src/binding.cc:184:20: error: use of undeclared identifier 'UV_READABLE'
      if (events & UV_READABLE) {
                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/cap/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/bin/node-gyp" "rebuild" "--target=0.11.13"
gyp ERR! cwd /Users/dominic/test/cap
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
```

Any chance of this module being updated?

**Comment by mscdex** [comment]
@postcasio @hynese I've nan-ified cap now, so it should compile and work on node v0.11+ and iojs. These changes are available in cap v0.0.11+.

**Comment by postcasio** [comment]
Awesome, thanks a lot!
